### ISSUE TITLE
Makefile: chown fails because $USER is not set

### ISSUE THREAD

**Issue by ghost** [epassaro/linux-photogrammetry-tools#12]
In order to make it work one has to set the `USER` env var.

`docker run -e USER=root` or `export USER=root` or something. It could be documented or if nothing is passed, default to `root`

**Comment by epassaro** [comment]
Yes, I know the current Docker workflow is not working as expected, but I do not have time to fix it :/

**Comment by epassaro** [comment]
Ok, I rolled back the file ownership stuff.

Now the image produce files created by `root` like a default Docker image.
