### ISSUE TITLE
compile error, no example folder ? ubuntu 18

### ISSUE THREAD

**Issue by tomg52** [epassaro/linux-photogrammetry-tools#8]
Hello 
I would like to try photogrametry, but i get the following compile error : 

 _Copying files...rsync: change_dir "/home/xxxxx/xxxxx/linux-photogrammetry-tools-2021.01-1//examples/kermit" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
Makefile:12: recipe for target 'images' failed
make: *** [images] Error 23_

Thanks !

**Comment by epassaro** [comment]
> Hello
> I would like to try photogrametry, but i get the following compile error :
> 
> _Copying files...rsync: change_dir "/home/xxxxx/xxxxx/linux-photogrammetry-tools-2021.01-1//examples/kermit" failed: No such file or directory (2) rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2] Makefile:12: recipe for target 'images' failed make: *** [images] Error 23_
> 
> Thanks !

You have an extra  "/" before "examples".

**Comment by tomg52** [comment]
I saw it, but this is not the reason.
Actually I have no example folder in the linux-photogrammetry-tools one.
I downloaded the source code from github.

**Comment by epassaro** [comment]
You don't need to download the source code, you need to download the compiled binaries from the releases section: https://github.com/epassaro/linux-photogrammetry-tools/releases/download/2021.01-1/lpt-2021.01-1.tar.gz
